// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiGTXhhci_ZQUhZPKJM9aiAUHA_sS2ctQ',
    appId: '1:209882233985:web:99424eb3035ccc0e476180',
    messagingSenderId: '209882233985',
    projectId: 'wemeet-7de9a',
    authDomain: 'wemeet-7de9a.firebaseapp.com',
    storageBucket: 'wemeet-7de9a.firebasestorage.app',
    measurementId: 'G-WBWR7MRRHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiIYkjiyMwBSB1Ab5Yupj91S3VP9cOYtA',
    appId: '1:209882233985:android:ab58fcc3ea2e43c6476180',
    messagingSenderId: '209882233985',
    projectId: 'wemeet-7de9a',
    storageBucket: 'wemeet-7de9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv6EaNCyYRaKid2yQraMf1EAh8_5_x1iQ',
    appId: '1:209882233985:ios:5949010938ea6d73476180',
    messagingSenderId: '209882233985',
    projectId: 'wemeet-7de9a',
    storageBucket: 'wemeet-7de9a.firebasestorage.app',
    iosBundleId: 'com.wemeetClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv6EaNCyYRaKid2yQraMf1EAh8_5_x1iQ',
    appId: '1:209882233985:ios:879f1844ff9a2336476180',
    messagingSenderId: '209882233985',
    projectId: 'wemeet-7de9a',
    storageBucket: 'wemeet-7de9a.firebasestorage.app',
    iosBundleId: 'com.example.wemeetClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiGTXhhci_ZQUhZPKJM9aiAUHA_sS2ctQ',
    appId: '1:209882233985:web:fab1336899e2bd68476180',
    messagingSenderId: '209882233985',
    projectId: 'wemeet-7de9a',
    authDomain: 'wemeet-7de9a.firebaseapp.com',
    storageBucket: 'wemeet-7de9a.firebasestorage.app',
    measurementId: 'G-GQGFVQEX1P',
  );

}