name: Build Dev Container

on:
  push:
    branches: [ "main" ]
    paths: 
      - '.devcontainer/**'
  workflow_dispatch:

jobs:
  call-reusable-build:
    name: Dokcer Build & Push
    uses: we-meet-project/CICD-template/.github/workflows/reusable-workflow.yml@main
    with:
      image-name: 'rlawodms364/we-meet-client'
      image-version: '1.0.0'
      dockerfile-path: '.devcontainer/Dockerfile'
    secrets: inherit
